export const pins = [
  {
    latitude: -36.840290871688765, 
    longitude: 174.75550413803697,
    title: 'Silo Park',
    description: 'Public park incorporating parts of a former industrial site, with outdoor concerts, films & markets.',
    icon: '../assets/silopark.jpg',
    link: 'https://www.silopark.co.nz/',
    category: 'landmark',
  },
  {
    latitude: -36.840961775472145,
    longitude: 174.7563019664318,
    title: 'Auckland Fish Market',
    description: 'Indoor-outdoor hub featuring stalls for fresh fish & counters serving informal seafood dishes.',
    icon: '../assets/aklfishmarket.jpg',
    link: 'https://www.afm.co.nz/',
    category: 'market',
  },
  {
    latitude: -36.84289174288559, 
    longitude: 174.75700022883566,
    title: 'Grid Auckland / John Lysaght Coworking Startup space',
    description: 'Based in Wynyard Quarter, GridAKL is both the place and the people that grow Auckland’s tech, innovation and entrepreneurial ecosystems.',
    icon: '../assets/gridakl.jpg',
    link: 'https://gridakl.com/',
    category: 'business',
  },
  {
    latitude: -36.83637242863989, 
    longitude: 174.7592185697383,
    title: 'The Big Wheel',
    description: 'At the top end of Wynyard Wharf one finds a giant axle connecting two giant cogwheels – eight tons apiece – relics from a steam dredge “Whakarire” where they transmitted the power to the bucket chain.',
    icon: '../assets/thebigwheel.jpg',
    link: 'N/A',
    category: 'landmark',
  },
  {
    latitude: -36.84084368399549, 
    longitude: 174.75817690268167,
    title: 'Good George North Wharf',
    description: 'Open since 2019, Good George serves award winning, New Zealand craft beers and artisan gintails with new and experimental flavours. Our kitchen offers a variety of cuisine catering to all dining needs from corporate functions to drinks with your good-est pals!  ',
    icon: '../assets/goodgeorge.jpg',
    link: 'https://www.goodgeorgenorthwharf.co.nz/',
    category: 'restaurant',
  },
  {
    latitude: -36.84084368399549, 
    longitude: 174.75817690268167,
    title: 'Good George North Wharf',
    description: 'Open since 2019, Good George serves award winning, New Zealand craft beers and artisan gintails with new and experimental flavours. Our kitchen offers a variety of cuisine catering to all dining needs from corporate functions to drinks with your good-est pals!  ',
    icon: '../assets/goodgeorge.jpg',
    link: 'http://www.baduzzi.co.nz/',
    category: 'restaurant',
  },
];  


